name: bullet
description: Bullet provides a quick, straightforward, and comprehensive list of activities that students may access online.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.1.4
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_database: ^10.0.14
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF-Pro
      fonts:
        - asset: lib/fonts/pro/SF-Pro-Display-Black.otf
          weight: 900
        - asset: lib/fonts/pro/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: lib/fonts/pro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: lib/fonts/pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: lib/fonts/pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: lib/fonts/pro/SF-Pro-Display-Regular.otf
        - asset: lib/fonts/pro/SF-Pro-Text-Light.otf
          weight: 300
        - asset: lib/fonts/pro/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: lib/fonts/pro/SF-Pro-Display-Ultralight.otf
          weight: 100