name: bullet
description: Bullet provides a quick, straightforward, and comprehensive list of activities that students may access online.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.1.4
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_database: ^10.0.14
  flutter_datetime_picker: ^1.5.1
  multi_select_flutter:
    path: "./multi_select_flutter-4.1.3/"
  emoji_picker_flutter: ^1.5.4
  google_fonts: ^4.0.3
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.2.0
  flutter_profile_picture: ^2.0.0
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.2
  universal_io: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: '>=1.6.2 <3.0.0'
  build_web_compilers: '>=2.12.0 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/emoji/
  fonts:
    - family: SF-Pro
      fonts:
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Black.otf
          weight: 900
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Regular.otf
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Text-Light.otf
          weight: 300
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Ultralight.otf
          weight: 100